name: attendance_app
description: App móvil de registro de asistencia offline-first con escáner QR y geofencing de 10 metros.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase para Backend/Base de Datos
  supabase_flutter: ^2.6.0

  # Escaneo de QR y Cámara
  mobile_scanner: ^5.1.1
  permission_handler: ^11.3.1

  # Geolocalización y distancia
  geolocator: ^13.0.1

  # Almacenamiento local para base de datos offline-first
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Control de conectividad
  connectivity_plus: ^6.0.3

  # Notificaciones locales en el celular
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1

  # Utilidades
  intl: ^0.19.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
